name: release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0

      - name: Extract version from Chart.yaml
        run: |
          VERSION=$(grep '^version:' charts/test-app/Chart.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if version already exists
        id: check_version
        run: |
          if gh release view "test-app-$VERSION" >/dev/null 2>&1; then
            echo "Release test-app-$VERSION already exists! Skipping..."
            echo "SKIP=true" >> $GITHUB_ENV
          else
            echo "SKIP=false" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Packaging
        if: env.SKIP == 'false'
        run: |
          echo "packaging"
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          helm package charts/test-app --destination=.cr-release-packages

      - name: Run chart-releaser
        if: env.SKIP == 'false'
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: test-app
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"